##### Model Hyperparameters #######
input_dim: 32
hidden_dim: 21
num_conv_layers: 9
conv_type: "nnconv"         # options: nnconv, genconv, mlpgenvconv
unique_conv_per_layer: true    # if each convolution layer should have its own set of weights, or if one set should be used universally
dropout: 0.3
batchnorm: true
heads: 1                    # ignored unless using multi-head layers
pooling: "mean" #"mean-max"             # options: mean, max, add, mean-max (see: https://arxiv.org/pdf/1811.01287)

num_mlp_layers: 3
mlp_hidden_dim: 64

########## Training Hyperparameters ##########
epochs: 15
batch_size: 16
lr: 0.001
weight_decay: 0.01
criterion: "huber"            # options: mse (mean square error), huber
huber_delta: 0.1              # only used by huber, determines the scale where it transitions from quadratic to linear

####### Cross-validation settings #######
num_folds: 5

####### Edge-Specific Hyperparameters ######
cutoff: 8
log_dist: false # if true, take negative log of normalized dist

########## Wandb params ########
project_name: "antibody_gnn"
