_wandb:
    value:
        cli_version: 0.23.0
        e:
            hb5r7ow1zv0f46pknsco5168allfpzq2:
                apple:
                    ecpuCores: 6
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "20401094656"
                codePath: gnn_train.py
                codePathLocal: gnn_train.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "245107195904"
                        used: "206784274432"
                email: alison_jarvis@berkeley.edu
                executable: /Users/alisonjarvis/Documents/MSSE/chem_277b/GNN Tuning/venv/bin/python
                host: Alisons-MacBook-Air.local
                memory:
                    total: "17179869184"
                os: macOS-15.3-arm64-arm-64bit
                program: /Users/alisonjarvis/Documents/MSSE/chem_277b/GNN Sweep/gnn_train.py
                python: CPython 3.11.14
                root: /Users/alisonjarvis/Documents/MSSE/chem_277b/GNN Sweep
                startedAt: "2025-12-10T02:09:55.428559Z"
                writerId: hb5r7ow1zv0f46pknsco5168allfpzq2
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 13
                - 16
            "4": 3.11.14
            "5": 0.23.0
            "12": 0.23.0
            "13": darwin-arm64
batch_size:
    value: 16
batchnorm:
    value: true
conv_type:
    value: nnconv
criterion:
    value: mse
cutoff:
    value: 4
dropout:
    value: 0.1
edge_dim:
    value: 5
epochs:
    value: 50
heads:
    value: 1
hidden_dim:
    value: 64
input_dim:
    value: 21
lr:
    value: 0.001
mlp_hidden_dim:
    value: 128
num_conv_layers:
    value: 3
num_folds:
    value: 5
num_mlp_layers:
    value: 3
output_dim:
    value: 1
pooling:
    value: mean
project_name:
    value: antibody_gnn
weight_decay:
    value: 1e-05
